using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TextProcessingFramework.Proto
{
    public class BaseTextProcessor
    {   
        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="name">Unique name of the processor.</param>
        /// <param name="inputLayers">Collection of unique names of layers required for the processor.</param>
        /// <param name="outputLayers">Collection of unique names layers generated by the processor.</param>
        public BaseTextProcessor(String name, IEnumerable<String> inputLayers, IEnumerable<String> outputLayers)
        {
            Name = name;
            _inputLayers.AddRange(inputLayers);
            _outputLayers.AddRange(outputLayers);
            if (_outputLayers.Count == 0)
                throw new InvalidOperationException("Empty output layers collection. Each processor must generate at least one layer!");
        }

        List<String> _inputLayers = new List<string>();
        List<String> _outputLayers = new List<string>();

        /// <summary>
        /// Unique name of the processor.
        /// </summary>
        public String Name
        {
            get;
            internal set;
        }
        /// <summary>
        /// Prototype of processing method.
        /// </summary>
        /// <param name="text">Processed object.</param>
        /// <returns>An array of the resulting layers.</returns>
        public virtual TextLayer[] Process(TextInfo text)
        {
            TextLayer[] result = null;

            if (text != null)
            {

                result = new TextLayer[_outputLayers.Count];
                for (int i = 0; i < _outputLayers.Count; ++i)
                {
                    result[i] = new TextLayer(_outputLayers[i], new List<BaseTextLayerItem> { new BaseTextLayerItem() });
                }
                
            }
            return result;
        }
        /// <summary>
        /// An array of unique names of layers required for the processor.
        /// </summary>
        public String[] InputLayerNames
        {
            get
            {
               return _inputLayers.ToArray();   
            }

        }
        /// <summary>
        /// An array of unique names layers generated by the processor.
        /// </summary>
        public String[] OutputLayerNames
        {
            get
            {
                return _outputLayers.ToArray();
            }
        }
    }
}
